### ISSUE TITLE
可以提供除了attentionuav7.yaml以外的其他的网络结构yaml进行测试吗？

### ISSUE THREAD

**Issue by Adonis2018** [huashu996/SLBAF-Net#3]
我在attentionuav7.yaml上使用可见光和红外进行训练的结果，并不如直接用yolov5n.yaml的结果，我认为attentionuav7.yaml的backbone1太简单了，可能效果不好，请问可以提供其他的yaml进行测试吗？
我在一篇博客上看到关于你的代码讲解，改文章提供的网络yaml如下面所示。我使用该yaml在这个项目代码中跑不通，如果我想使用下面的yaml，该如何与此项目进行匹配。
```yaml
# 双模型态度
nc: 7  
depth_multiple: 0.33  
width_multiple: 0.50
 
#边界框的设置
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
 
backbone1:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2 #64代表通道数，3表示3*3的卷积核，2代表步长为2,2表示分两组卷积
   #320×320×32
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   #160×160×64
   [-1, 3, C3, [128]],
   #160×160×64
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   #80×80×128
   [-1, 6, C3, [256]],
   #80×80×128
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   #40×40×256
   [-1, 9, C3, [512]],
   #40×40×256
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   #20×20×512
   [-1, 3, C3, [1024]],
   #20×20×512
   [-1, 1, SPPF, [1024, 5]],  # 9
   #20×20×512
  ]
 

backbone2:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  #10
   #320×320×32
   [-1, 1, Conv, [128, 3, 2]],  # 
   #160×160×64
   [-1, 3, C3, [128]], 
   #160×160×64 
   [-1, 1, Conv, [256, 3, 2]],
   #80×80×128  
   [-1, 6, C3, [256]],  # 14
   #80×80×128
   [[-1, 4], 1, Concat2, [1]],  #
   #80×80×256
   [-1, 6, C3, [256]],  #16
   #80×80×128
   [14, 1, Conv, [512, 3, 2]],  # 
   #40×40×256
   [-1, 9, C3, [512]],
   #40×40×256
   [[-1, 6], 1, Concat2, [1]],  #
   #40×40×512
   [-1, 6, C3, [512]],  #20
   #40×40×256
   [17, 1, Conv, [1024, 3, 2]],  # 
   #20×20×512
   [[-1, 9], 1, Concat2, [1]],  # 
   #20×20×1024
   [-1, 3, C3, [1024]],
   #20×20×512
   [-1, 1, SPPF, [1024, 5]],  #24
   #20×20×512
  ]
 
# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
  #20×20×256
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   #40×40×256
   [[-1, 20], 1, Concat, [1]],  # cat backbone P4
    #40×40×512
   [-1, 3, C3, [512, False]],  # 28
   #40×40×256
 
   [-1, 1, Conv, [256, 1, 1]],
   #40×40×128
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   #80×80×128
   [[-1, 16], 1, Concat, [1]],  # cat backbone P3
   #80×80×256
   [-1, 3, C3, [256, False]],  # 32 (P3/8-small)
   #80×80×128
 
   [-1, 1, Conv, [512, 3, 2]],
   #40×40×256
   [[-1, 28], 1, Concat, [1]],  # cat head P4
   #40×40×512
   [-1, 3, C3, [512, False]],  # 35 (P4/16-medium)
   #40×40×256
 
   [-1, 1, Conv, [1024, 3, 2]],
   #20×20×512
   [[-1, 24], 1, Concat, [1]],  # cat head P5
   #20×20×1024
   [-1, 3, C3, [1024, False]],  # 38 (P5/32-large)
   #20×20×512
 
   [[32, 35, 38], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```
